// Package crypto provides AES-256-GCM authenticated encryption for lab credentials.
// The master key is read from disk and used to encrypt/decrypt secrets in-memory;
// plaintext values are never written to persistent storage.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
	"os"
)

// Cipher provides authenticated encryption and decryption of credential data.
type Cipher interface {
	// Encrypt encrypts plaintext and returns a base64-encoded ciphertext string.
	Encrypt(plaintext []byte) (string, error)
	// Decrypt decodes and decrypts a base64-encoded ciphertext string.
	Decrypt(ciphertext string) ([]byte, error)
}

// AESCipher implements Cipher using AES-256-GCM authenticated encryption.
// The random 12-byte nonce is prepended to the ciphertext and encoded together
// as base64 for storage: base64(nonce || ciphertext || GCM-tag).
type AESCipher struct {
	key []byte
}

// NewAESCipher creates an AESCipher by reading the 32-byte master key from masterKeyPath.
// The key file must contain exactly 32 bytes (generated by petri init).
func NewAESCipher(masterKeyPath string) (*AESCipher, error) {
	key, err := os.ReadFile(masterKeyPath)
	if err != nil {
		return nil, fmt.Errorf("reading master key from %s: %w", masterKeyPath, err)
	}
	return newFromKey(key)
}

// NewAESCipherFromKey creates an AESCipher directly from a 32-byte key slice.
// Primarily used in tests or when the key is provided programmatically.
func NewAESCipherFromKey(key []byte) (*AESCipher, error) {
	return newFromKey(key)
}

func newFromKey(key []byte) (*AESCipher, error) {
	if len(key) != 32 {
		return nil, fmt.Errorf("master key must be exactly 32 bytes, got %d", len(key))
	}
	keyCopy := make([]byte, 32)
	copy(keyCopy, key)
	return &AESCipher{key: keyCopy}, nil
}

// Encrypt encrypts plaintext using AES-256-GCM with a randomly generated 12-byte nonce.
// Output format: base64(nonce || ciphertext || GCM-authentication-tag).
func (c *AESCipher) Encrypt(plaintext []byte) (string, error) {
	block, err := aes.NewCipher(c.key)
	if err != nil {
		return "", fmt.Errorf("creating AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("creating GCM: %w", err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", fmt.Errorf("generating nonce: %w", err)
	}
	// Seal appends (ciphertext || tag) after the nonce so the full blob is nonce||ciphertext||tag.
	sealed := gcm.Seal(nonce, nonce, plaintext, nil)
	return base64.StdEncoding.EncodeToString(sealed), nil
}

// Decrypt decodes the base64 ciphertext and decrypts it using AES-256-GCM.
// Returns an error if the ciphertext is malformed or authentication fails.
func (c *AESCipher) Decrypt(ciphertext string) ([]byte, error) {
	data, err := base64.StdEncoding.DecodeString(ciphertext)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	block, err := aes.NewCipher(c.key)
	if err != nil {
		return nil, fmt.Errorf("creating AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("creating GCM: %w", err)
	}
	nonceSize := gcm.NonceSize()
	if len(data) < nonceSize {
		return nil, fmt.Errorf("ciphertext too short (%d bytes, need at least %d)", len(data), nonceSize)
	}
	nonce, sealed := data[:nonceSize], data[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, sealed, nil)
	if err != nil {
		return nil, fmt.Errorf("decrypting ciphertext: %w", err)
	}
	return plaintext, nil
}
