// Package git provisions git repositories on GitHub and populates them with
// realistic commit history generated by the commits generator.
package git

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jaimegago/petri/pkg/generators/commits"
)

// Config holds credentials and settings for the git provisioner.
type Config struct {
	// Token is the GitHub personal access token used for API calls and HTTPS push.
	Token string
	// GitHubBaseURL overrides the GitHub API base URL.
	// Defaults to "https://api.github.com". Set for GitHub Enterprise.
	GitHubBaseURL string
}

// CreateOptions configures a new repository to provision.
type CreateOptions struct {
	// Owner is the GitHub username or organisation that will own the repository.
	Owner string
	// Name is the repository name.
	Name string
	// Description is the optional repository description.
	Description string
	// Private sets the repository visibility.
	Private bool
	// IsOrg indicates that Owner is a GitHub organisation.
	// When true the org-scoped API endpoint is used.
	IsOrg bool
	// DefaultBranch is the name of the initial branch. Defaults to "main".
	DefaultBranch string
	// Commits is the ordered list of commits to create.
	// When empty a single bootstrap commit is created automatically.
	Commits []commits.CommitSpec
	// WorkDir is an optional directory in which to initialise the local clone.
	// When empty a temporary directory is created and removed after the push.
	WorkDir string
}

// DeleteOptions configures a repository deletion.
type DeleteOptions struct {
	// Owner is the GitHub username or organisation.
	Owner string
	// Name is the repository name.
	Name string
}

// RepoInfo describes a repository that was successfully provisioned.
type RepoInfo struct {
	Name          string `json:"name"`
	FullName      string `json:"full_name"`
	CloneURL      string `json:"clone_url"`
	SSHURL        string `json:"ssh_url"`
	DefaultBranch string `json:"default_branch"`
}

// Provisioner manages git repositories for labs.
type Provisioner interface {
	// Create creates a remote repository and populates it with commit history.
	Create(ctx context.Context, opts CreateOptions) (*RepoInfo, error)
	// Delete removes a remote repository.
	Delete(ctx context.Context, opts DeleteOptions) error
}

// gitHubClient abstracts GitHub API calls so tests can inject a fake.
type gitHubClient interface {
	createRepo(ctx context.Context, req createRepoRequest) (*RepoInfo, error)
	deleteRepo(ctx context.Context, owner, name string) error
}

// repoOps abstracts local git CLI operations so tests can inject a fake.
type repoOps interface {
	init(ctx context.Context, dir, branch string) error
	addRemote(ctx context.Context, dir, name, url string) error
	addAll(ctx context.Context, dir string) error
	commit(ctx context.Context, dir string, spec commits.CommitSpec) error
	push(ctx context.Context, dir, remote, branch string) error
}

type provisioner struct {
	cfg    Config
	client gitHubClient
	ops    repoOps
}

// New returns a Provisioner backed by the real GitHub API and the local git CLI.
func New(cfg Config) Provisioner {
	baseURL := cfg.GitHubBaseURL
	if baseURL == "" {
		baseURL = "https://api.github.com"
	}
	return &provisioner{
		cfg:    cfg,
		client: newAPIClient(cfg.Token, baseURL),
		ops:    &cliRepo{},
	}
}

// newWithDeps injects client and repoOps dependencies; used in tests.
func newWithDeps(cfg Config, client gitHubClient, ops repoOps) Provisioner {
	return &provisioner{cfg: cfg, client: client, ops: ops}
}

// Create provisions a GitHub repo and populates it with the commit history.
func (p *provisioner) Create(ctx context.Context, opts CreateOptions) (*RepoInfo, error) {
	branch := opts.DefaultBranch
	if branch == "" {
		branch = "main"
	}

	// Create the remote repository.
	info, err := p.client.createRepo(ctx, createRepoRequest{
		Owner:       opts.Owner,
		Name:        opts.Name,
		Description: opts.Description,
		Private:     opts.Private,
		IsOrg:       opts.IsOrg,
	})
	if err != nil {
		return nil, fmt.Errorf("creating remote repo %s/%s: %w", opts.Owner, opts.Name, err)
	}

	// Prepare the local working directory.
	workDir, cleanup, err := resolveWorkDir(opts.WorkDir)
	if err != nil {
		_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
		return nil, fmt.Errorf("resolving work dir: %w", err)
	}
	defer cleanup()

	// Initialise the local git repository.
	if err := p.ops.init(ctx, workDir, branch); err != nil {
		_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
		return nil, fmt.Errorf("git init: %w", err)
	}

	// Add the authenticated remote.
	authedURL := embedToken(info.CloneURL, p.cfg.Token)
	if err := p.ops.addRemote(ctx, workDir, "origin", authedURL); err != nil {
		_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
		return nil, fmt.Errorf("git remote add: %w", err)
	}

	// Use provided commits or a single bootstrap placeholder.
	commitList := opts.Commits
	if len(commitList) == 0 {
		commitList = bootstrapCommits()
	}

	// Write files and create each commit.
	for i, spec := range commitList {
		if err := writeCommitFiles(workDir, spec, i); err != nil {
			_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
			return nil, fmt.Errorf("writing files for commit %d: %w", i, err)
		}
		if err := p.ops.addAll(ctx, workDir); err != nil {
			_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
			return nil, fmt.Errorf("git add for commit %d: %w", i, err)
		}
		if err := p.ops.commit(ctx, workDir, spec); err != nil {
			_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
			return nil, fmt.Errorf("git commit %d %q: %w", i, spec.Message, err)
		}
	}

	// Push the history to the remote.
	if err := p.ops.push(ctx, workDir, "origin", branch); err != nil {
		_ = p.client.deleteRepo(ctx, opts.Owner, opts.Name)
		return nil, fmt.Errorf("git push: %w", err)
	}

	info.DefaultBranch = branch
	return info, nil
}

// Delete removes a remote repository.
func (p *provisioner) Delete(ctx context.Context, opts DeleteOptions) error {
	if err := p.client.deleteRepo(ctx, opts.Owner, opts.Name); err != nil {
		return fmt.Errorf("deleting repo %s/%s: %w", opts.Owner, opts.Name, err)
	}
	return nil
}

// ─── helpers ──────────────────────────────────────────────────────────────────

// resolveWorkDir returns the directory to use and a no-op or remove cleanup func.
func resolveWorkDir(requested string) (string, func(), error) {
	if requested != "" {
		return requested, func() {}, nil
	}
	dir, err := os.MkdirTemp("", "petri-git-*")
	if err != nil {
		return "", func() {}, fmt.Errorf("creating temp dir: %w", err)
	}
	return dir, func() { _ = os.RemoveAll(dir) }, nil
}

// embedToken injects a GitHub PAT into an HTTPS clone URL.
// e.g. https://github.com/owner/repo.git → https://<token>@github.com/owner/repo.git
func embedToken(cloneURL, token string) string {
	if token == "" {
		return cloneURL
	}
	return strings.Replace(cloneURL, "https://", "https://"+token+"@", 1)
}

// writeCommitFiles writes spec.Files into the working directory.
// A unique .petri-meta tracking file is always written to guarantee each
// commit has at least one staged change.
func writeCommitFiles(workDir string, spec commits.CommitSpec, idx int) error {
	// Write a unique tracking file so git always has something to stage.
	tracking := fmt.Sprintf(
		"generated-by: petri\ncommit-sequence: %d\ntimestamp: %s\n",
		idx, spec.Timestamp.Format(time.RFC3339),
	)
	if err := writeFile(workDir, ".petri-meta", tracking); err != nil {
		return fmt.Errorf("writing tracking file: %w", err)
	}
	// Write any additional files from the commit spec.
	for path, content := range spec.Files {
		if path == ".petri-meta" {
			// Already handled above; skip to avoid overwriting unique content.
			continue
		}
		if err := writeFile(workDir, path, content); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

// writeFile creates parent directories as needed and writes content to path
// relative to workDir.
func writeFile(workDir, relPath, content string) error {
	abs := filepath.Join(workDir, filepath.FromSlash(relPath))
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(abs), err)
	}
	if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", relPath, err)
	}
	return nil
}

// bootstrapCommits returns a single placeholder commit used when no history is provided.
func bootstrapCommits() []commits.CommitSpec {
	return []commits.CommitSpec{
		{
			Message: "init: bootstrap repository",
			Files:   map[string]string{"README.md": "# Repository\n\nManaged by Petri.\n"},
		},
	}
}
