// Package chaos provides random, non-deterministic fault injection against running Kubernetes labs.
// It defines the core types and interfaces used by ChaosRunner and consumed by the instrumentation
// package. Adding a new fault type requires only implementing the Fault interface and registering
// it in the faults map passed to NewRunner — no existing code needs modification.
package chaos

import (
	"context"
	"time"
)

// FaultType identifies a category of fault that can be injected into a running lab.
type FaultType string

const (
	// FaultKillPod deletes a running pod, triggering a restart cycle via the owning controller.
	FaultKillPod FaultType = "kill_pod"
	// FaultRestartDeployment performs a rolling restart of a Deployment.
	FaultRestartDeployment FaultType = "restart_deployment"
	// FaultCPUPressure injects artificial CPU load inside a running pod using stress-ng.
	FaultCPUPressure FaultType = "cpu_pressure"
	// FaultMemPressure injects artificial memory pressure inside a running pod using stress-ng.
	FaultMemPressure FaultType = "memory_pressure"
	// FaultCorruptConfigMap overwrites a key in a ConfigMap with an invalid sentinel value.
	FaultCorruptConfigMap FaultType = "corrupt_configmap"
	// FaultRevokeServiceAccount deletes the legacy token Secrets bound to a ServiceAccount.
	FaultRevokeServiceAccount FaultType = "revoke_serviceaccount"
	// FaultNetworkLatency adds artificial network latency to a pod's primary network interface
	// using the Linux tc/netem subsystem. Requires CAP_NET_ADMIN or a privileged pod.
	FaultNetworkLatency FaultType = "network_latency"
	// FaultScaleToZero scales a Deployment to zero replicas, making it unavailable.
	FaultScaleToZero FaultType = "scale_to_zero"
)

// TargetResource identifies a Kubernetes resource that may be the target of a fault.
type TargetResource struct {
	// Namespace is the Kubernetes namespace containing the resource.
	Namespace string `yaml:"namespace" json:"namespace"`
	// Name is the resource name. For pod-targeting faults that resolve from a controller,
	// this may be a Deployment name or a label selector (e.g. "app=frontend").
	Name string `yaml:"name" json:"name"`
	// Kind is the Kubernetes resource kind (e.g. "Pod", "Deployment", "ConfigMap").
	Kind string `yaml:"kind" json:"kind"`
}

// FaultEvent records a single fault injection attempt and its outcome.
// It is emitted through EventEmitter so the instrumentation package can build a timeline.
type FaultEvent struct {
	// ID is a unique identifier (UUID) for this event.
	ID string `json:"id"`
	// FaultType is the kind of fault that was injected.
	FaultType FaultType `json:"fault_type"`
	// Target is the Kubernetes resource that was targeted.
	Target TargetResource `json:"target"`
	// StartedAt is when the fault injection began.
	StartedAt time.Time `json:"started_at"`
	// EndedAt is when the fault injection completed or failed.
	EndedAt time.Time `json:"ended_at"`
	// Success reports whether the fault was injected without error.
	Success bool `json:"success"`
	// Error contains the error message when Success is false.
	Error string `json:"error,omitempty"`
	// Metadata holds fault-specific supplementary key/value pairs.
	Metadata map[string]string `json:"metadata,omitempty"`
	// ScenarioStep is set when this event was generated by a ScenarioRunner; it holds
	// the step name so the instrumentation package can correlate events to scenario steps.
	ScenarioStep string `json:"scenario_step,omitempty"`
	// ExpectedDiagnosis is the human-readable description of what Joe should detect after
	// this fault fires. Set by ScenarioRunner from the scenario YAML; unused by ChaosRunner.
	ExpectedDiagnosis string `json:"expected_diagnosis,omitempty"`
}

// EventEmitter receives fault events from a ChaosRunner or ScenarioRunner.
// Implementations must be safe for concurrent use from multiple goroutines.
type EventEmitter interface {
	// Emit records a fault event. Emit must not block the caller.
	Emit(event FaultEvent)
}

// Fault executes a single category of fault against a Kubernetes resource.
// Implementations should be idempotent where possible so that injecting the same
// fault twice does not corrupt the chaos session or leave the cluster in an
// unrecoverable state.
type Fault interface {
	// Type returns the FaultType this implementation handles.
	Type() FaultType
	// Execute performs fault injection against target using the provided kube client.
	// params carries fault-specific configuration (e.g. "latency_ms": "200").
	// The caller wraps Execute's return value in a FaultEvent; Execute itself should
	// not emit events.
	Execute(ctx context.Context, kube KubeClient, target TargetResource, params map[string]string) error
}

// FaultSpec describes a single fault within a ChaosProfile, including when and how
// often it should fire.
type FaultSpec struct {
	// Type is the fault to inject.
	Type FaultType `yaml:"type" json:"type"`
	// Probability is the likelihood [0.0, 1.0] of this fault being chosen in any given
	// selection round. A value of 1.0 means always chosen; 0.0 means never.
	Probability float64 `yaml:"probability" json:"probability"`
	// Parameters carries fault-specific configuration. Each fault documents its
	// supported keys.
	Parameters map[string]string `yaml:"parameters,omitempty" json:"parameters,omitempty"`
}

// ChaosProfile describes a set of faults and the timing policy governing a chaos session.
type ChaosProfile struct {
	// Name is a human-readable identifier for the profile.
	Name string `yaml:"name" json:"name"`
	// Faults is the pool of possible faults, each with its own firing probability.
	Faults []FaultSpec `yaml:"faults" json:"faults"`
	// Targets is the pool of Kubernetes resources that faults may target.
	// ChaosRunner picks a random target for each fault injection.
	Targets []TargetResource `yaml:"targets" json:"targets"`
	// MinInterval is the minimum wait between consecutive fault injections.
	// Defaults to 10s when zero.
	MinInterval time.Duration `yaml:"min_interval" json:"min_interval"`
	// MaxInterval is the maximum wait between consecutive fault injections.
	// Defaults to 2× MinInterval when zero or less than MinInterval.
	MaxInterval time.Duration `yaml:"max_interval" json:"max_interval"`
	// Duration limits the chaos session lifetime. Zero means the session runs until
	// the context passed to ChaosRunner.Run is cancelled.
	Duration time.Duration `yaml:"duration,omitempty" json:"duration,omitempty"`
}
